services:
  # The main Node.js API service for production
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
      # This will automatically use the final stage of the Dockerfile
    container_name: motion-worker-prod
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001" 
    command: pnpm start